/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenants"];
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["connectorHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestConnectorLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enrollConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/log-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLogBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/log-batches/{connector}/{batch}/legal-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setLogLegalHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/log-batches/{connector}/{batch}/retry-archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryLogArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDomains"];
        put?: never;
        post: operations["createDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listActions"];
        put?: never;
        post: operations["proposeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvestigations"];
        put?: never;
        post: operations["startInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEdge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            status: "onboarding" | "active" | "suspended";
            /** @enum {string} */
            isolation_mode: "shared" | "dedicated";
            monitoring_approved: boolean;
            operations_approved: boolean;
            kill_switch: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Component: {
            name: string;
            kind: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unknown" | "stale";
            /** Format: date-time */
            observed_at?: string | null;
        };
        Domain: {
            /** Format: uuid */
            id: string;
            hostname: string;
            surface: string;
            status: string;
            certificate_status: string;
            /** Format: date-time */
            verified_at?: string | null;
            /** Format: date-time */
            expires_at: string;
        };
        Connector: {
            /** Format: uuid */
            id: string;
            name: string;
            version: string;
            capabilities: string[];
            status: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: date-time */
            last_telemetry_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Overview: {
            /** Format: uuid */
            id: string;
            name: string;
            status: string;
            isolation_mode: string;
            monitoring_approved: boolean;
            operations_approved: boolean;
            kill_switch: boolean;
            connected_connectors: number;
            open_incidents: number;
            pending_approvals: number;
            notification_recipients?: string[];
            components: components["schemas"]["Component"][];
        };
        Incident: {
            /** Format: uuid */
            id: string;
            title: string;
            severity: string;
            status: string;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            acknowledged_at?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            summary: string;
        };
        Action: {
            /** Format: uuid */
            id: string;
            target: string;
            action_type: string;
            purpose: string;
            impact: string;
            status: string;
            requested_by: string;
            approved_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            approval_expires_at?: string | null;
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string | null;
            actor: string;
            event_type: string;
            resource: string;
            correlation_id: string;
            outcome: string;
            /** Format: date-time */
            occurred_at: string;
            detail: {
                [key: string]: unknown;
            };
        };
        Notification: {
            /** Format: uuid */
            id: string;
            recipient: string;
            status: string;
            attempts: number;
            /** Format: date-time */
            delivered_at?: string | null;
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
        };
        MetricSeries: {
            metric: string;
            unit: string;
            window: string;
            points: {
                /** Format: date-time */
                at: string;
                value: number;
            }[];
        };
        ConnectorMetric: {
            /** @enum {string} */
            name: "host_cpu_usage_pct" | "host_memory_used_pct" | "host_root_disk_used_pct" | "host_network_rx_bytes_total" | "host_network_tx_bytes_total" | "postgres_connections" | "postgres_rollbacks_total" | "postgres_replica_count" | "postgres_replay_backlog_bytes" | "valkey_used_memory_bytes" | "valkey_connected_clients" | "valkey_evicted_keys_total";
            value: number;
            unit: string;
        };
        ConnectorHeartbeat: {
            /**
             * Format: uuid
             * @description Must match the authenticated connector's tenant
             */
            tenant_id: string;
            /**
             * Format: uuid
             * @description Must match the authenticated connector
             */
            connector_id: string;
            /** @description Required when components is nonempty; retained across retries */
            batch_id?: string;
            version: string;
            components: {
                name: string;
                /** @enum {string} */
                kind: "tcp" | "postgres" | "valkey" | "host";
                /** @enum {string} */
                status: "healthy" | "degraded" | "unknown";
                /** Format: date-time */
                observed_at: string;
                latency_ms?: number;
                metrics?: components["schemas"]["ConnectorMetric"][];
            }[];
        };
        ApprovedLogSource: {
            name: string;
            /** @enum {string} */
            kind: "postgres" | "valkey" | "vault" | "aegiscore";
            path_sha256: string;
        };
        ConnectorLogBatch: {
            /**
             * Format: uuid
             * @description Must match the authenticated connector's tenant
             */
            tenant_id: string;
            /**
             * Format: uuid
             * @description Must match the authenticated connector
             */
            connector_id: string;
            batch_id: string;
            source_name: string;
            /** @enum {string} */
            source_kind: "postgres" | "valkey" | "vault" | "aegiscore";
            path_sha256: string;
            /** Format: date-time */
            collected_at: string;
            lines: string[];
        };
        LogBatchMetadata: {
            /** Format: uuid */
            connector_id: string;
            batch_id: string;
            source_name: string;
            source_kind: string;
            /** Format: date-time */
            collected_at: string;
            /** Format: date-time */
            received_at: string;
            line_count: number;
            /** @enum {string} */
            status: "hot" | "archived" | "blocked";
            archive_attempts: number;
            /** Format: date-time */
            archive_retry_at: string;
            cleanup_attempts: number;
            /** Format: date-time */
            cleanup_retry_at: string;
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: date-time */
            hot_deleted_at?: string | null;
            legal_hold: boolean;
        };
        Investigation: {
            /** Format: uuid */
            id: string;
            requested_by: string;
            status: string;
            summary: string;
            uncertainty: string;
            evidence: {
                [key: string]: unknown;
            }[];
            sources: string[];
            provider: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subject?: string;
                        roles?: string[];
                    };
                };
            };
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tenant"][];
                    };
                };
            };
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    isolation_mode?: string;
                    authorization_record: string;
                    notification_recipients: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Incident"][];
                    };
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                window?: "1h" | "24h" | "7d";
                /** @description One of the named numeric metrics in ConnectorMetric */
                metric?: string;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeries"];
                };
            };
        };
    };
    connectorHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorHeartbeat"];
            };
        };
        responses: {
            /** @description Batch accepted or already recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or unauthorized telemetry */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector credential revoked or unknown */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingestConnectorLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorLogBatch"];
            };
        };
        responses: {
            /** @description Encrypted batch persisted and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or oversized batch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector credential revoked or unknown */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector or source not approved */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issueEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    capabilities?: ("tcp_health" | "host_metrics" | "postgres_health" | "valkey_health" | "service_logs")[];
                    log_sources?: components["schemas"]["ApprovedLogSource"][];
                };
            };
        };
        responses: {
            /** @description One-time token with server-approved capabilities and log sources */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid enrollment scope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enrollConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    name: string;
                    version: string;
                    /** @description If supplied */
                    capabilities?: string[];
                };
            };
        };
        responses: {
            /** @description Tenant-bound connector identity created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid or requested scope differs from approval */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLogBatches: {
        parameters: {
            query?: {
                limit?: number;
                before?: string;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped log metadata only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LogBatchMetadata"][];
                    };
                };
            };
        };
    };
    setLogLegalHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                connector: string;
                batch: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    engaged: boolean;
                };
            };
        };
        responses: {
            /** @description Legal hold changed and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryLogArchive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                connector: string;
                batch: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocked archive batch returned to the retry queue and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDomains: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Domain"][];
                    };
                };
            };
        };
    };
    createDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    hostname: string;
                    surface: string;
                };
            };
        };
        responses: {
            /** @description Challenge created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer connectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Connector"][];
                    };
                };
            };
        };
    };
    listActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Action"][];
                    };
                };
            };
        };
    };
    proposeAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target: string;
                    action_type: string;
                    purpose: string;
                    parameters: {
                        [key: string]: unknown;
                    };
                    impact: string;
                    preconditions: string;
                    rollback_plan: string;
                    verification_steps: string;
                };
            };
        };
        responses: {
            /** @description Proposed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInvestigations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investigations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Investigation"][];
                    };
                };
            };
        };
    };
    startInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                    };
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Notification"][];
                    };
                };
            };
        };
    };
    getEdge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edge status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        provider?: string;
                        status?: string;
                        origin_protected?: boolean;
                        /** Format: date-time */
                        last_checked_at?: string | null;
                    };
                };
            };
        };
    };
}
