FROM node:24-alpine3.24 AS build
WORKDIR /src
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
COPY web ./web
COPY contracts ./contracts
RUN npm run build

FROM node:24-alpine3.24
ENV NODE_ENV=production
WORKDIR /src
COPY --from=build /src/package.json /src/package.json
COPY --from=build /src/node_modules /src/node_modules
COPY --from=build /src/web /src/web
USER node
EXPOSE 3000
CMD ["./node_modules/.bin/next", "start", "web", "-H", "0.0.0.0"]
