import Link from 'next/link';
import { Activity, ArrowLeft, ClipboardCheck, Clock3, PlugZap, ScrollText, ShieldCheck, Settings2 } from 'lucide-react';
import { api, type Overview, type Incident, type Action, type AuditEvent, type Notification, type MetricSeries } from '@/lib/api';
import { DataState, Kpi, PageHead, SectionTitle, Status, Time } from '@/components/ui';
import { MetricChart } from '@/components/metric-chart';

export default async function CustomerDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const [overview,incidents,actions,audit,notifications,metrics]=await Promise.all([api<Overview>(`/tenants/${id}/overview`),api<{items:Incident[]}>(`/tenants/${id}/incidents`),api<{items:Action[]}>(`/tenants/${id}/actions`),api<{items:AuditEvent[]}>(`/tenants/${id}/audit?limit=8`),api<{items:Notification[]}>(`/tenants/${id}/notifications`),api<MetricSeries>(`/tenants/${id}/metrics?window=24h`)]);const o=overview.data;return <><Link className="backlink" href="/customers"><ArrowLeft size={15}/> All customers</Link><PageHead eyebrow="CUSTOMERS / ENVIRONMENT" title={o?.name||'Customer environment'} description="Health, operational access, and customer-visible history." action={o&&<span className="head-status"><Status value={o.status}/></span>}/>{overview.error?<DataState error={overview.error}/>:o&&<>
  <div className="customer-meta"><span>Tenant <strong className="mono">{o.id.slice(0,8)}…</strong></span><span>Isolation <strong className="capitalize">{o.isolation_mode}</strong></span><span>Monitoring <Status value={o.monitoring_approved?'active':'pending'}/></span><span>Operations <Status value={o.operations_approved?'active':'pending'}/></span></div>
  {o.kill_switch&&<div className="alert-banner">Customer kill switch is engaged. Operational dispatch is blocked.</div>}
  <div className="kpi-row"><Kpi label="Connected connectors" value={o.connected_connectors} note="Seen within 5 minutes" icon={PlugZap}/><Kpi label="Open incidents" value={o.open_incidents} note="Customer scoped" icon={Activity}/><Kpi label="Pending approvals" value={o.pending_approvals} note="Exact action parameters" icon={ClipboardCheck}/><Kpi label="Inventory components" value={o.components.length} note="Stale status shown separately" icon={ShieldCheck}/></div>
  <div className="split-section"><section><SectionTitle title="Component health" subtitle="Latest authorized connector report"/>{o.components.length?<div className="table-frame"><table><thead><tr><th>Component</th><th>Kind</th><th>Health</th><th>Observed</th></tr></thead><tbody>{o.components.map(c=><tr key={c.name}><td className="table-primary">{c.name}</td><td className="capitalize">{c.kind}</td><td><Status value={c.status}/></td><td><Time value={c.observed_at}/></td></tr>)}</tbody></table></div>:<DataState empty title="No approved telemetry yet"/>}</section><section><SectionTitle title="Probe latency" subtitle="Time series / last 24 hours"/><MetricChart series={metrics.data}/></section></div>
  <div className="split-section lower"><section><SectionTitle title="Recent incidents" href={`/incidents?tenant=${id}`} subtitle="Alerts and investigation history"/>{incidents.data?.items.length?<div className="compact-list">{incidents.data.items.slice(0,4).map(i=><div className="compact-row" key={i.id}><span className="severity-mark"/><div><strong>{i.title}</strong><small><Time value={i.opened_at}/></small></div><Status value={i.status}/></div>)}</div>:<DataState empty title="No incidents recorded"/>}</section><section><SectionTitle title="Recent access" href={`/audit?tenant=${id}`} subtitle="Customer-visible audit events"/>{audit.data?.items.length?<div className="compact-list">{audit.data.items.slice(0,4).map(e=><div className="compact-row" key={e.id}><span className="event-icon"><ScrollText size={15}/></span><div><strong>{e.event_type.replaceAll('.',' ')}</strong><small>{e.actor} · <Time value={e.occurred_at}/></small></div></div>)}</div>:<DataState empty title="No access recorded"/>}</section></div>
  <div className="detail-links"><Link href={`/customers/${id}/onboarding`}><Settings2 size={18}/> Onboarding & connectors <strong>Manage</strong></Link><Link href={`/approvals?tenant=${id}`}><ClipboardCheck size={18}/> Operation requests <strong>{actions.data?.items.length||0}</strong></Link><Link href={`/audit?tenant=${id}`}><ScrollText size={18}/> Audit trail <strong>{audit.data?.items.length||0} recent</strong></Link><Link href={`/settings?tenant=${id}`}><Clock3 size={18}/> Notification delivery <strong>{notifications.data?.items.length||0} records</strong></Link></div>
  </>}</>}
