'use client';
import { useState } from 'react';
import type { Overview, Domain, Connector } from '@/lib/api';
import { Status, Time } from './ui';
export function OnboardingControls({tenant,overview,initialDomains,initialConnectors}:{tenant:string;overview:Overview;initialDomains:Domain[];initialConnectors:Connector[]}){
 const [domains,setDomains]=useState<Domain[]>(initialDomains),[connectors,setConnectors]=useState<Connector[]>(initialConnectors),[challenge,setChallenge]=useState<{txt_name:string;txt_value:string}|null>(null),[enrollment,setEnrollment]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const [d,c]=await Promise.all([fetch(`/api/proxy/tenants/${tenant}/domains`,{cache:'no-store'}),fetch(`/api/proxy/tenants/${tenant}/connectors`,{cache:'no-store'})]);if(d.ok)setDomains((await d.json()).items);if(c.ok)setConnectors((await c.json()).items)}
 async function post(path:string,body:unknown={}){setBusy(true);setMessage('');try{const response=await fetch(`/api/proxy/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');await load();return result}catch(e){setMessage(e instanceof Error?e.message:'Request failed');return null}finally{setBusy(false)}}
 async function addDomain(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const input=e.currentTarget.elements.namedItem('hostname') as HTMLInputElement;const result=await post(`tenants/${tenant}/domains`,{hostname:input.value,surface:'customer'});if(result){setChallenge({txt_name:result.txt_name,txt_value:result.txt_value});input.value='';setMessage('DNS challenge created. Publish the TXT record, then verify.')}}
 return <div className="onboarding-layout"><section className="onboarding-step"><div className="step-number">01</div><div className="step-body"><h2>Verify customer domain</h2><p>Domain control identifies the onboarding request. It does not authorize network access or operations.</p><form className="inline-form" onSubmit={addDomain}><label>Hostname<input name="hostname" placeholder="customer.example" required/></label><button className="button" disabled={busy}>Create DNS challenge</button></form>{challenge&&<div className="challenge"><strong>Publish DNS TXT record</strong><code>{challenge.txt_name}</code><code>{challenge.txt_value}</code><small>Expires in 24 hours. The token is shown only now.</small></div>}{domains.length>0&&<div className="step-list">{domains.map(d=><div key={d.id}><div><strong>{d.hostname}</strong><small>Expires <Time value={d.expires_at}/></small></div><Status value={d.status}/>{d.status==='pending'&&<button className="button button-small" onClick={()=>void post(`tenants/${tenant}/domains/${d.id}/verify`)} disabled={busy}>Verify DNS</button>}</div>)}</div>}</div></section>
 <section className="onboarding-step"><div className="step-number">02</div><div className="step-body"><h2>Enroll customer connector</h2><p>The connector sends outbound TLS heartbeats and locally approved TCP, host, PostgreSQL, or Valkey health signals. Enrollment tokens expire after 15 minutes.</p><button className="button" disabled={busy} onClick={async()=>{const result=await post(`tenants/${tenant}/enrollment-tokens`);if(result)setEnrollment(result.token)}}>Issue one-time token</button>{enrollment&&<div className="challenge"><strong>One-time enrollment token</strong><code>{enrollment}</code><small>Copy now. It will not be displayed again.</small></div>}{connectors.length>0&&<div className="step-list">{connectors.map(c=><div key={c.id}><div><strong>{c.name}</strong><small>Version {c.version} · Last seen <Time value={c.last_seen_at}/></small></div><Status value={c.status}/>{c.status!=='revoked'&&<button className="button button-small danger" onClick={()=>void post(`tenants/${tenant}/connectors/${c.id}/revoke`)} disabled={busy}>Revoke</button>}</div>)}</div>}</div></section>
 <section className="onboarding-step"><div className="step-number">03</div><div className="step-body"><h2>Approve monitoring & operations</h2><p>Customer authorization and notification recipients are recorded. Monitoring requires a verified domain and enrolled connector. Operations require a separate approval and per-action policy.</p><div className="approval-controls"><div><span>Monitoring</span><Status value={overview.monitoring_approved?'active':'pending'}/><button className="button button-small" disabled={busy||overview.monitoring_approved} onClick={async()=>{if(await post(`tenants/${tenant}/monitoring/approve`))window.location.reload()}}>Approve monitoring</button></div><div><span>Operations</span><Status value={overview.operations_approved?'active':'pending'}/><button className="button button-small" disabled={busy||overview.operations_approved} onClick={async()=>{if(await post(`tenants/${tenant}/operations/approve`))window.location.reload()}}>Approve operations</button></div></div><p className="step-disclosure">Telemetry: component name, kind, status, probe latency, and timestamps. Processing: control plane database and configured metrics backend. Access and actions produce customer audit events and queued notifications. No business records are requested.</p></div></section>
 {message&&<div className="form-error" role="status">{message}</div>}</div>
}
