import Link from 'next/link';
import { AlertCircle, ArrowRight, CircleHelp, DatabaseZap, Radio } from 'lucide-react';
export function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:React.ReactNode}) {return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="head-actions">{action}</div>}</div>}
export function Status({value}:{value:string}) {const v=value.toLowerCase();const kind=['healthy','active','connected','delivered','success','verified'].includes(v)?'good':['degraded','pending','queued','onboarding','provisioning','simulated'].includes(v)?'warn':['failed','dead','disconnected','suspended','denied'].includes(v)?'bad':'muted';return <span className={`status status-${kind}`}><span className="status-dot"/>{value.replaceAll('_',' ')}</span>}
export function Time({value}:{value?:string|null}) {if(!value)return <span className="muted">—</span>;return <time dateTime={value} title={new Date(value).toLocaleString()}>{new Date(value).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC</time>}
export function DataState({error,empty,title}:{error?:string;empty?:boolean;title?:string}) {if(error)return <div className="data-state"><AlertCircle size={24}/><h2>{error.includes('Sign in')?'Sign in required':'Data unavailable'}</h2><p>{error}</p>{error.includes('Sign in')&&<Link className="button" href="/auth/login">Sign in <ArrowRight size={15}/></Link>}</div>;if(empty)return <div className="data-state"><CircleHelp size={24}/><h2>{title||'Nothing to show yet'}</h2><p>Records will appear here when the authorized workflow begins.</p></div>;return null}
export function Kpi({label,value,note,icon:Icon}:{label:string;value:string|number;note:string;icon:typeof Radio}) {return <div className="kpi"><div className="kpi-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{note}</small></div>}
export function SectionTitle({title,subtitle,href,link}:{title:string;subtitle?:string;href?:string;link?:string}) {return <div className="section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{href&&<Link href={href}>{link||'View all'} <ArrowRight size={15}/></Link>}</div>}
export function EmptyChart(){return <div className="empty-chart"><div className="chart-grid"/><DatabaseZap size={25}/><strong>No telemetry received</strong><span>Graphs appear after an approved connector reports metrics.</span></div>}
